import { ArrowRight, BookOpen, BrainCircuit, Code2, Globe2, GraduationCap, Laptop, Lightbulb, MonitorPlay, Phone, School, ShieldCheck, Smartphone, Sparkles, Star, Target, Trophy, Users } from "lucide-react";
import DemoForm from "@/components/DemoForm";

const courses = [
  { icon: Code2, title: "Visual Coding & Programming", classes: "Class 4–10", text: "Start with Scratch and logic, then move into Python programming and mini projects." },
  { icon: Globe2, title: "Web Development", classes: "Class 6–10", text: "Learn HTML, CSS, JavaScript basics and build websites and interactive projects." },
  { icon: Smartphone, title: "Mobile App Basics", classes: "Class 7–10", text: "Create simple mobile app prototypes and understand app logic and UI flow." },
  { icon: BrainCircuit, title: "AI Basics", classes: "Class 6–10", text: "Understand AI, prompts, responsible AI use and simple classification demos." },
  { icon: ShieldCheck, title: "Cyber Safety", classes: "Class 4–10", text: "Learn passwords, phishing awareness, online privacy and safe internet habits." },
];
const levels = [
  { title: "Digital Explorer", classes: "Class 4–6", points: ["Scratch coding", "Logic games", "Animations", "Cyber safety basics", "Mini projects"] },
  { title: "Tech Builder", classes: "Class 7–8", points: ["Python basics", "HTML & CSS", "App logic", "AI tools", "Portfolio projects"] },
  { title: "Future Engineer", classes: "Class 9–10", points: ["JavaScript basics", "Python projects", "AI demo", "Web app projects", "Capstone project"] },
];
const features = [
  { icon: MonitorPlay, title: "Live + Recorded Learning", text: "Weekly live classes with recorded lesson access for revision." },
  { icon: Laptop, title: "Student LMS Portal", text: "Lessons, notes, assignments, quizzes and project submissions in one place." },
  { icon: Users, title: "Parent Progress Updates", text: "Parents receive progress, attendance and project updates." },
  { icon: Trophy, title: "Certificates & Showcase", text: "Students complete projects and receive certificates after evaluation." },
];

export default function HomePage() {
  return (
    <main>
      <nav className="nav"><a className="brand" href="#home"><div className="logoMark">DG</div><div><strong>Digital Gurukul Nepal</strong><span>Learn • Practice • Create • Succeed</span></div></a><div className="navLinks"><a href="#courses">Courses</a><a href="#levels">Levels</a><a href="#pricing">Pricing</a><a href="/login">Login</a></div><a className="navCta" href="#register">Register Now</a></nav>
      <section id="home" className="hero"><div className="heroContent"><div className="badge"><Sparkles size={16} /> Coding, AI & Future Skills for School Students</div><h1>Nepal’s affordable coding academy for <span>Class 4–10 students.</span></h1><p>Digital Gurukul Nepal helps young learners build real skills in visual coding, Python, web development, mobile app basics, AI basics and cyber safety through practical learning.</p><div className="heroActions"><a className="primaryBtn" href="#register">Book Free Demo Class <ArrowRight size={18} /></a><a className="secondaryBtn" href="#courses">View Course Plan</a></div><div className="trustRow"><div><Star size={18} /> Project-based learning</div><div><Star size={18} /> Parent progress updates</div><div><Star size={18} /> School partnership model</div></div></div><div className="heroCard"><div className="cardTop"><GraduationCap size={34} /><span>Annual Foundation Program</span></div><h2>NPR 2,000/year</h2><p>Affordable future-skills learning for every Nepali student.</p><div className="miniGrid"><div><strong>4–10</strong><span>Class Focus</span></div><div><strong>2K</strong><span>Annual Package</span></div><div><strong>Projects</strong><span>Learning Style</span></div><div><strong>Hybrid</strong><span>Mode</span></div></div><div className="codePreview"><span>student.learn()</span><span>student.practice()</span><span>student.create_project()</span><span>student.succeed()</span></div></div></section>
      <section className="partnersStrip"><span>Designed for</span><b>Students</b><b>Parents</b><b>Schools</b><b>Instructors</b></section>
      <section className="section twoCol"><div><div className="sectionTag">About Us</div><h2>Building future-ready digital confidence from school level.</h2></div><div><p>Digital Gurukul Nepal is an IT education and technology training institute focused only on school students. Our goal is to make coding and digital skills accessible, practical and affordable for Class 4–10 students across Nepal.</p></div></section>
      <section id="courses" className="section"><div className="sectionHeader"><div><div className="sectionTag">Course Domains</div><h2>One platform, multiple future-skill domains.</h2></div><p>The curriculum moves step-by-step from visual coding to Python, web development, app logic, AI basics and cyber safety.</p></div><div className="courseGrid">{courses.map((course) => { const Icon = course.icon; return <article className="courseCard" key={course.title}><Icon size={32} /><span>{course.classes}</span><h3>{course.title}</h3><p>{course.text}</p></article>; })}</div></section>
      <section id="levels" className="section"><div className="sectionHeader"><div><div className="sectionTag">Class-wise Learning Path</div><h2>Simple, structured and age-appropriate.</h2></div></div><div className="levelGrid">{levels.map((level, index) => <article className="levelCard" key={level.title}><div className="levelNumber">0{index + 1}</div><span>{level.classes}</span><h3>{level.title}</h3><ul>{level.points.map(p => <li key={p}>{p}</li>)}</ul></article>)}</div></section>
      <section className="section platform"><div className="sectionHeader"><div><div className="sectionTag">Platform Features</div><h2>Mini LMS + admission system + progress tracking.</h2></div><p>Start lean with essential features first. Then scale toward parent dashboards, certificates, school panels and gamification.</p></div><div className="featureGrid">{features.map((item) => { const Icon = item.icon; return <article className="featureCard" key={item.title}><Icon size={30} /><h3>{item.title}</h3><p>{item.text}</p></article>; })}</div><div className="phaseBox"><div className="phaseItem"><span>Phase 1</span><h3>Launch MVP</h3><p>Website, admission form, student portal, course videos, assignments and admin dashboard.</p></div><div className="phaseItem"><span>Phase 2</span><h3>Trust Features</h3><p>Parent portal, certificates, progress reports, quizzes and project portfolio.</p></div><div className="phaseItem"><span>Phase 3</span><h3>Scale Platform</h3><p>School dashboard, online payment, gamification, badges, leaderboards and AI tutor.</p></div></div></section>
      <section id="pricing" className="section pricing"><div className="pricingCard"><div><div className="sectionTag">Affordable Package</div><h2>Basic Annual Coding & Future Skills Program</h2><p>Best for school students who want to start coding early and build digital confidence throughout the year.</p></div><div className="priceBox"><span>Annual Fee</span><strong>NPR 2,000</strong><small>per student / year</small><a href="#register">Enroll Student</a></div></div><div className="includedGrid"><div><BookOpen /> Weekly live learning</div><div><MonitorPlay /> Recorded support lessons</div><div><Target /> Assignments and quizzes</div><div><Lightbulb /> Monthly mini projects</div><div><Trophy /> Completion certificate</div><div><Users /> Parent progress updates</div></div></section>
      <section className="section schoolCta"><div><School size={42} /><h2>School partnership program</h2><p>We help schools introduce affordable coding, AI and cyber safety learning to students without building a full internal technology department.</p></div><a href="#register">Partner With Us <ArrowRight size={18} /></a></section>
      <section id="register" className="section register"><div className="registerText"><div className="sectionTag">Free Demo Class</div><h2>Register interest for your child or school.</h2><p>This form is connected to backend API and stores inquiries in PostgreSQL.</p><div className="contactMini"><Phone size={20} /><span>WhatsApp / Phone: +977-98XXXXXXXX</span></div></div><DemoForm /></section>
      <footer className="footer"><div><div className="brand"><div className="logoMark">DG</div><strong>Digital Gurukul Nepal</strong></div><p>A school-level coding and future-skills LMS for Nepal.</p></div><div><h4>Courses</h4><a href="#courses">Coding</a><a href="#courses">Web Development</a><a href="#courses">AI Basics</a><a href="#courses">Cyber Safety</a></div><div><h4>Contact</h4><a href="mailto:info@digitalgurukulnepal.com">info@digitalgurukulnepal.com</a><a href="tel:+9779800000000">+977-98XXXXXXXX</a><a href="#register">Book Free Demo</a></div></footer>
    </main>
  );
}
